ServerName localhost

<VirtualHost *:80>
    DocumentRoot "/var/www/html/public_html"
    DirectoryIndex index.php index.html index.htm
    
    <Directory "/var/www/html/public_html">
        AllowOverride All
        Require all granted
        Options FollowSymLinks MultiViews
    </Directory>

    ErrorLog "/var/log/apache2/cubespace_error.log"
    CustomLog "/var/log/apache2/cubespace_access.log" combined
</VirtualHost>

<VirtualHost *:8080>
    DocumentRoot "/var/www/html/public_html"
    DirectoryIndex index.php index.html index.htm
    
    <Directory "/var/www/html/public_html">
        AllowOverride All
        Require all granted
        Options FollowSymLinks MultiViews
    </Directory>
</VirtualHost>
