ServerName localhost

<VirtualHost *:80>
    DocumentRoot /var/www/html
    DirectoryIndex index.php index.html index.htm
    
    <Directory /var/www/html>
        AllowOverride All
        Require all granted
        Options FollowSymLinks MultiViews
        
        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            RewriteRule ^(.*)$ index.php [QSA,L]
        </IfModule>
    </Directory>

    ErrorLog /var/log/apache2/error.log
    CustomLog /var/log/apache2/access.log combined
</VirtualHost>

<VirtualHost *:8080>
    DocumentRoot /var/www/html
    DirectoryIndex index.php index.html index.htm
    
    <Directory /var/www/html>
        AllowOverride All
        Require all granted
        Options FollowSymLinks MultiViews
        
        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            RewriteRule ^(.*)$ index.php [QSA,L]
        </IfModule>
    </Directory>
</VirtualHost>
